/* eslint-disable jsx-a11y/no-static-element-interactions, jsx-a11y/no-noninteractive-element-interactions */
"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { parseCSV, MAX_FILE_SIZE } from "@/lib/csv";
import { generateSummary, money, stats } from "@/lib/finance";
import { applyRule, DEFAULT_RULES, recategorizeUnreviewed } from "@/lib/rules";
import { LocalDataStore } from "@/lib/storage";
import { CATEGORIES, type Category, type Movement, type Rule } from "@/lib/types";
import { parseXLSX } from "@/lib/xlsx";

type Page = "panel" | "movimientos" | "importar" | "categorias" | "privacidad";
type MovementFilters = { query?: string; category?: Category; month?: string; type?: "Gastos" | "Ingresos" | "Transferencias" };
const NAV: { id: Page; label: string }[] = [
  { id: "panel", label: "Panel" },
  { id: "movimientos", label: "Movimientos" },
  { id: "categorias", label: "Categorías y reglas" },
  { id: "privacidad", label: "Configuración" },
];
const MONTHS = ["Ene", "Feb", "Mar", "Abr", "May", "Jun", "Jul", "Ago", "Sep", "Oct", "Nov", "Dic"];
const COLORS = ["#1f8a70", "#f0a45d", "#6e7fcb", "#db6d76", "#64a6a1", "#a57bb5", "#d0a231"];
const displayDate = (date: string) => date ? date.split("-").reverse().join("-") : "—";

export default function Home() {
  const store = useMemo(() => new LocalDataStore(), []);
  const [page, setPage] = useState<Page>("panel"); const [movements, setMovements] = useState<Movement[]>([]);
  const [rules, setRules] = useState<Rule[]>(DEFAULT_RULES); const [year, setYear] = useState(2026); const [ready, setReady] = useState(false);
  const [movementFilters, setMovementFilters] = useState<MovementFilters>({});
  const [toast, setToast] = useState("");
  useEffect(() => { const timer = window.setTimeout(() => { const storedRules = store.loadRules(); const savedRules = storedRules?.some((rule) => rule.custom) ? [...DEFAULT_RULES.map((base) => storedRules.find((rule) => rule.id === base.id && rule.custom) || base), ...storedRules.filter((rule) => !DEFAULT_RULES.some((base) => base.id === rule.id))] : DEFAULT_RULES; const saved = store.load(); setRules(savedRules); if (saved) setMovements(recategorizeUnreviewed(saved, savedRules)); setReady(true); }, 0); return () => window.clearTimeout(timer); }, [store]);
  useEffect(() => { if (ready) store.save(movements); }, [movements, ready, store]);
  useEffect(() => { if (ready) store.saveRules(rules); }, [rules, ready, store]);
  useEffect(() => { if (!ready) return; const timer = window.setTimeout(() => setMovements((current) => recategorizeUnreviewed(current, rules)), 0); return () => window.clearTimeout(timer); }, [rules, ready]);
  const notify = (message: string) => { setToast(message); window.setTimeout(() => setToast(""), 3200); };
  const navigate = (next: Page) => { setMovementFilters({}); setPage(next); window.scrollTo({ top: 0, behavior: "smooth" }); };
  const openFilteredMovements = (filters: MovementFilters) => { setMovementFilters(filters); setPage("movimientos"); window.scrollTo({ top: 0, behavior: "smooth" }); };
  return <div className="app-shell">
    <AppHeader page={page} navigate={navigate} />
    <main>{page === "panel" && <Dashboard movements={movements} year={year} setYear={setYear} navigate={navigate} openFilteredMovements={openFilteredMovements} />}{page === "movimientos" && <Movements items={movements} setItems={setMovements} navigate={navigate} initialFilters={movementFilters} />}{page === "importar" && <Importer onImport={(rows) => { setMovements((old) => [...rows, ...old]); notify(`${rows.length} movimientos importados`); navigate("movimientos"); }} />}{page === "categorias" && <Rules rules={rules} setRules={setRules} movements={movements} setMovements={setMovements} notify={notify} />}{page === "privacidad" && <Privacy store={store} setMovements={setMovements} notify={notify} />}</main>
    {toast && <div className="toast" role="status">{toast}</div>}
  </div>;
}

function AppHeader({ page, navigate }: { page: Page; navigate: (p: Page) => void }) { return <header className="app-header"><div className="header-inner"><button className="brand" onClick={() => navigate("panel")} aria-label="MiBalance · Ir al panel"><span>€</span></button><nav aria-label="Navegación principal">{NAV.map((item) => <button key={item.id} className={page === item.id ? "active" : ""} onClick={() => navigate(item.id)} aria-current={page === item.id ? "page" : undefined}>{item.label}</button>)}</nav></div></header>; }

function Dashboard({ movements, year, setYear, navigate, openFilteredMovements }: { movements: Movement[]; year: number; setYear: (y: number) => void; navigate: (p: Page) => void; openFilteredMovements: (filters: MovementFilters) => void }) {
  const s = stats(movements, year); const max = Math.max(...s.months.flatMap((m) => [m.expenses, m.income]), 1); const summary = generateSummary(movements, year);
  return <section className="page dashboard"><div className="page-title"><div><h1>Tu resumen financiero</h1></div><label className="year-picker">Año <select value={year} onChange={(e) => setYear(Number(e.target.value))}><option>2026</option><option>2025</option><option>2024</option></select></label></div>
    {!s.spend ? <Empty title="No hay datos para este año" text="Importa un CSV o cambia de año para ver tu análisis." action="Importar movimientos" onAction={() => navigate("importar")} /> : <><div className="metrics"><Metric label="Gastos totales" value={money(s.spend)} trend={`${s.comparison >= 0 ? "Aumento" : "Descenso"} del ${Math.abs(s.comparison).toFixed(1).replace(".", ",")} % frente a ${year - 1}`} tone="coral" /><Metric label="Ingresos totales" value={money(s.earned)} trend="Ingresos registrados" tone="green" /><Metric label="Balance" value={money(s.balance)} trend={s.balance >= 0 ? "Ingresas más de lo que gastas" : "Gastas más de lo que ingresas"} tone="blue" /></div>
      <div className="dashboard-grid"><article className="card chart-card span2"><CardHead title="Evolución mensual" subtitle="Ingresos y gastos" action={() => openFilteredMovements({ type: "Gastos" })} /><div className="legend"><span><i className="dot income" />Ingresos</span><span><i className="dot expense" />Gastos</span></div><div className="bar-chart" aria-label="Gráfico de evolución mensual">{s.months.map((m, index) => <button className="bar-group" key={m.month} aria-label={`Ver gastos de ${m.month}`} onClick={() => openFilteredMovements({ month: String(index + 1).padStart(2, "0"), type: "Gastos" })}><span className="bars"><i className="bar income" style={{ height: `${Math.max((m.income / max) * 160, m.income ? 5 : 0)}px` }} /><i className="bar expense" style={{ height: `${Math.max((m.expenses / max) * 160, m.expenses ? 5 : 0)}px` }} /></span><small>{m.month}</small></button>)}</div></article>
        <article className="card"><CardHead title="Por categorías" subtitle="Distribución de gastos" action={() => openFilteredMovements({ type: "Gastos" })} /><div className="category-list">{s.category.slice(0, 6).map(([name, value], i) => <button key={name} onClick={() => openFilteredMovements({ category: name as Category, type: "Gastos" })}><i style={{ background: COLORS[i % COLORS.length] }} /><span><b>{name}</b><small>{((value / s.spend) * 100).toFixed(1).replace(".", ",")} %</small></span><strong>{money(value)}</strong></button>)}</div></article>
        <article className="card insight span2"><div><p className="eyebrow">RESUMEN INTELIGENTE · GENERADO LOCALMENTE</p><h2>Tu año en palabras sencillas</h2><p>{summary}</p><small>Basado únicamente en cálculos de tus datos. No se ha enviado información a servicios externos.</small></div></article>
        <article className="card savings-rate"><p className="eyebrow">TASA DE AHORRO ANUAL</p><strong>{s.savingsRate.toFixed(1).replace(".", ",")} %</strong><p>{money(s.saved)} enviados a ahorro de {money(s.earned)} ingresados</p><button onClick={() => openFilteredMovements({ category: "Ahorro", type: "Transferencias" })}>Ver movimientos</button></article>
        <article className="card merchant-card"><CardHead title="Dónde gastas más" subtitle="Top 20 comercios" action={() => openFilteredMovements({ type: "Gastos" })} /><ol className="merchant-list">{s.merchants.slice(0, 20).map(([name, value], i) => <li key={name}><button onClick={() => openFilteredMovements({ query: name, type: "Gastos" })}><span>{i + 1}</span><b>{name}</b><strong>{money(value)}</strong></button></li>)}</ol></article>
        <article className="card"><CardHead title="Pagos recurrentes" subtitle="Top 20 pagos recurrentes" action={() => openFilteredMovements({ type: "Gastos" })} /><div className="recurring">{s.recurring.slice(0, 20).map((r) => <button key={r.merchant} onClick={() => openFilteredMovements({ query: r.merchant, type: "Gastos" })}><span>{r.merchant.slice(0, 1)}</span><p><b>{r.merchant}</b><small>{r.frequency}</small></p><strong>{money(r.amount)}</strong></button>)}</div></article>
        <article className="card month-highlight"><p className="eyebrow">MES CON MAYOR GASTO</p><div><p><b>{s.highest?.month}</b><small>{money(s.highest?.expenses || 0)}</small></p></div><button onClick={() => { const monthIndex = s.highest ? s.months.findIndex((item) => item === s.highest) : -1; if (monthIndex >= 0) openFilteredMovements({ month: String(monthIndex + 1).padStart(2, "0"), type: "Gastos" }); }}>Ver movimientos</button></article>
        </div></>}
  </section>;
}
function Metric({ label, value, trend, tone }: { label: string; value: string; trend: string; tone: string }) { return <article className={`metric ${tone}`}><p>{label}</p><strong>{value}</strong><small>{trend}</small></article>; }
function CardHead({ title, subtitle, action }: { title: string; subtitle: string; action: () => void }) { return <div className="card-head"><div><h2>{title}</h2><p>{subtitle}</p></div><button onClick={action} aria-label={`Ver ${title}`}>Ver</button></div>; }

function Movements({ items, setItems, navigate, initialFilters }: { items: Movement[]; setItems: React.Dispatch<React.SetStateAction<Movement[]>>; navigate: (p: Page) => void; initialFilters: MovementFilters }) {
  const [query, setQuery] = useState(initialFilters.query ?? ""); const [category, setCategory] = useState(initialFilters.category ?? "Todas"); const [month, setMonth] = useState(initialFilters.month ?? "Todos"); const [type, setType] = useState(initialFilters.type ?? "Todos"); const [sort, setSort] = useState("date-desc"); const [selected, setSelected] = useState<string[]>([]); const [detail, setDetail] = useState<Movement | null>(null);
  const filtered = useMemo(() => items.filter((m) => (!query || `${m.concept ?? ""} ${m.description} ${m.merchant} ${m.reference ?? ""}`.toLowerCase().includes(query.toLowerCase())) && (category === "Todas" || m.category === category) && (month === "Todos" || m.date.slice(5, 7) === month) && (type === "Todos" || type === "Gastos" && m.amount < 0 || type === "Ingresos" && m.amount > 0 || type === "Transferencias" && ["Ahorro", "Otras transferencias"].includes(m.category))).sort((a, b) => sort === "amount" ? Math.abs(b.amount) - Math.abs(a.amount) : sort === "date-asc" ? a.date.localeCompare(b.date) : b.date.localeCompare(a.date)), [items, query, category, month, type, sort]);
  const updateCategory = (ids: string[], next: Category) => setItems((old) => old.map((m) => ids.includes(m.id) ? { ...m, category: next, status: "revisado", reason: "Categoría corregida manualmente" } : m));
  return <section className="page"><div className="page-title"><div><h1>Movimientos</h1><p>Consulta, corrige y entiende cada apunte.</p></div><button className="primary" onClick={() => navigate("importar")}>Importar archivo</button></div><div className="toolbar card"><label className="search"><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Buscar comercio o descripción" aria-label="Buscar comercio o descripción" /></label><select value={category} onChange={(e) => setCategory(e.target.value)}><option>Todas</option>{CATEGORIES.map((x) => <option key={x}>{x}</option>)}</select><select value={month} onChange={(e) => setMonth(e.target.value)}><option>Todos</option>{MONTHS.map((x, i) => <option key={x} value={String(i + 1).padStart(2, "0")}>{x}</option>)}</select><select value={type} onChange={(e) => setType(e.target.value)}><option>Todos</option><option>Gastos</option><option>Ingresos</option><option>Transferencias</option></select><select value={sort} onChange={(e) => setSort(e.target.value)}><option value="date-desc">Más recientes</option><option value="date-asc">Más antiguos</option><option value="amount">Mayor importe</option></select></div>
    {selected.length > 0 && <div className="bulk"><b>{selected.length} seleccionados</b><select defaultValue="" onChange={(e) => { if (e.target.value) updateCategory(selected, e.target.value as Category); setSelected([]); }}><option value="" disabled>Clasificar como…</option>{CATEGORIES.map((x) => <option key={x}>{x}</option>)}</select><button onClick={() => setSelected([])}>Cancelar</button></div>}
    <div className="table-card card"><div className="table-summary"><b>{filtered.length} movimientos</b></div><div className="table-scroll"><table><thead><tr><th><input type="checkbox" aria-label="Seleccionar todos" checked={selected.length === filtered.length && !!filtered.length} onChange={(e) => setSelected(e.target.checked ? filtered.map((m) => m.id) : [])} /></th><th>Fecha Oper</th><th>Fecha Valor</th><th>Concepto</th><th>Descripción</th><th>Referencia</th><th>Importe</th><th>Categoría</th><th>Estado</th></tr></thead><tbody>{filtered.map((m) => <tr key={m.id}><td><input type="checkbox" aria-label={`Seleccionar ${m.description}`} checked={selected.includes(m.id)} onChange={() => setSelected((old) => old.includes(m.id) ? old.filter((x) => x !== m.id) : [...old, m.id])} /></td><td className="date-cell">{displayDate(m.date)}</td><td className="date-cell">{displayDate(m.valueDate || m.date)}</td><td><b>{m.concept || "—"}</b></td><td><button className="movement-name description-cell" onClick={() => setDetail(m)}><b>{m.description}</b></button></td><td className="reference-cell">{m.reference || "—"}</td><td className={m.amount > 0 ? "positive" : "negative"}><b>{m.amount > 0 ? "+" : "−"}{money(Math.abs(m.amount))}</b></td><td><select className="category-pill" value={m.category} onChange={(e) => updateCategory([m.id], e.target.value as Category)}>{CATEGORIES.map((x) => <option key={x}>{x}</option>)}</select></td><td><span className={`status ${m.status}`}>{m.status === "revisado" ? "Revisado" : "Pendiente"}</span></td></tr>)}</tbody></table></div><div className="movement-cards">{filtered.map((m) => <article key={m.id} className="movement-card"><label className="movement-check"><input type="checkbox" aria-label={`Seleccionar ${m.description}`} checked={selected.includes(m.id)} onChange={() => setSelected((old) => old.includes(m.id) ? old.filter((x) => x !== m.id) : [...old, m.id])} /></label><button className="movement-card-main" onClick={() => setDetail(m)}><span className="movement-icon" aria-hidden="true">{m.merchant.slice(0, 1).toUpperCase()}</span><span className="movement-copy"><b>{m.description}</b><small>{displayDate(m.date)} · {m.merchant}</small></span><strong className={m.amount > 0 ? "positive" : "negative"}>{m.amount > 0 ? "+" : "−"}{money(Math.abs(m.amount))}</strong></button><select className="category-pill" aria-label={`Categoría de ${m.description}`} value={m.category} onChange={(e) => updateCategory([m.id], e.target.value as Category)}>{CATEGORIES.map((x) => <option key={x}>{x}</option>)}</select></article>)}</div>{!filtered.length && <Empty title="No encontramos movimientos" text="Prueba a cambiar los filtros o importa un nuevo archivo." />}</div>
    {detail && <div className="modal-backdrop" onMouseDown={() => setDetail(null)}><aside className="drawer" onMouseDown={(e) => e.stopPropagation()}><button className="close" onClick={() => setDetail(null)}>×</button><p className="eyebrow">DETALLE DEL MOVIMIENTO</p><h2>{detail.description}</h2><strong className={detail.amount > 0 ? "positive big" : "negative big"}>{money(detail.amount)}</strong><dl><div><dt>Fecha</dt><dd>{detail.date}</dd></div><div><dt>Comercio normalizado</dt><dd>{detail.merchant}</dd></div><div><dt>Cuenta</dt><dd>{detail.account}</dd></div><div><dt>Origen</dt><dd>{detail.source.toUpperCase()}</dd></div></dl><div className="reason"><b>¿Por qué esta categoría?</b><p>{detail.reason}</p></div><label>Categoría<select value={detail.category} onChange={(e) => { updateCategory([detail.id], e.target.value as Category); setDetail({ ...detail, category: e.target.value as Category }); }}>{CATEGORIES.map((x) => <option key={x}>{x}</option>)}</select></label><label className="check"><input type="checkbox" checked={!!detail.ownTransfer} onChange={(e) => { const value = e.target.checked; setItems((old) => old.map((m) => m.id === detail.id ? { ...m, ownTransfer: value, category: value ? "Otras transferencias" : m.category } : m)); setDetail({ ...detail, ownTransfer: value }); }} /> Transferencia entre mis cuentas</label></aside></div>}
  </section>;
}

function Importer({ onImport }: { onImport: (rows: Movement[]) => void }) {
  const input = useRef<HTMLInputElement>(null); const [file, setFile] = useState<File | null>(null); const [preview, setPreview] = useState<Movement[]>([]); const [errors, setErrors] = useState(0); const [message, setMessage] = useState(""); const [dateFormat, setDateFormat] = useState("DD/MM/YYYY"); const [expensePositive, setExpensePositive] = useState(false);
  const load = async (chosen: File) => { setMessage(""); const extension = chosen.name.toLowerCase().split(".").pop(); if (!extension || !["csv", "xlsx"].includes(extension)) return setMessage("Selecciona un archivo CSV o XLSX válido."); if (chosen.size > MAX_FILE_SIZE) return setMessage("El archivo supera el límite de 5 MB."); try { const result = extension === "xlsx" ? await parseXLSX(chosen, dateFormat, expensePositive) : parseCSV(await chosen.text(), dateFormat, expensePositive); setFile(chosen); setPreview(result.rows); setErrors(result.errors); } catch (e) { setMessage(e instanceof Error ? e.message : "No se pudo leer el archivo."); } };
  return <section className="page"><div className="page-title"><div><h1>Importar movimientos</h1><p>Tu Excel o CSV se procesa aquí, en tu dispositivo.</p></div><a className="secondary" href="/ejemplo-ibercaja.csv" download>Descargar CSV de ejemplo</a></div><div className="import-layout"><div className="card import-card"><div className="step"><span>1</span><div><h2>Selecciona tu archivo</h2><p>Excel XLSX o CSV de Ibercaja · Máximo 5 MB</p></div></div><button className={`dropzone ${file ? "has-file" : ""}`} onClick={() => input.current?.click()} onDragOver={(e) => e.preventDefault()} onDrop={(e) => { e.preventDefault(); if (e.dataTransfer.files[0]) load(e.dataTransfer.files[0]); }}><b>{file ? file.name : "Arrastra tu archivo aquí"}</b><small>{file ? `${(file.size / 1024).toFixed(1)} KB · listo para revisar` : "o pulsa para seleccionarlo"}</small></button><input ref={input} hidden type="file" accept=".csv,.xlsx,text/csv,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" onChange={(e) => e.target.files?.[0] && load(e.target.files[0])} />{message && <p className="error" role="alert">{message}</p>}<div className="import-options"><label>Formato de fecha<select value={dateFormat} onChange={(e) => setDateFormat(e.target.value)}><option>DD/MM/YYYY</option><option>YYYY-MM-DD</option><option>MM/DD/YYYY</option></select></label><label className="check"><input type="checkbox" checked={expensePositive} onChange={(e) => setExpensePositive(e.target.checked)} /> Los gastos aparecen en positivo</label></div></div><aside className="card security"><h3>Tu información se queda contigo</h3><p>No subimos el archivo ni registramos su contenido. Se procesa localmente y se protege frente a fórmulas peligrosas.</p><ul><li>Excel y CSV</li><li>Coma o punto decimal</li><li>Cargo y abono separados</li><li>Caracteres españoles</li></ul></aside></div>
    {preview.length > 0 && <div className="card preview"><div className="step"><span>2</span><div><h2>Revisa antes de importar</h2><p>{preview.length} filas válidas · {errors} con error</p></div><button className="primary" onClick={() => onImport(preview)}>Importar {preview.length} movimientos</button></div><div className="table-scroll"><table><thead><tr><th>Fecha</th><th>Descripción</th><th>Cuenta</th><th>Categoría sugerida</th><th>Importe</th><th>Resultado</th></tr></thead><tbody>{preview.slice(0, 8).map((m) => <tr key={m.id}><td>{m.date}</td><td>{m.description}</td><td>{m.account}</td><td>{m.category}</td><td className={m.amount > 0 ? "positive" : "negative"}>{money(m.amount)}</td><td><span className="status revisado">Válido</span></td></tr>)}</tbody></table></div></div>}
  </section>;
}

function Rules({ rules, setRules, movements, setMovements, notify }: { rules: Rule[]; setRules: (r: Rule[]) => void; movements: Movement[]; setMovements: (m: Movement[]) => void; notify: (s: string) => void }) {
  const [term, setTerm] = useState(""); const [category, setCategory] = useState<Category>("Otros"); const [editing, setEditing] = useState<string | null>(null); const [draftTerm, setDraftTerm] = useState(""); const [draftCategory, setDraftCategory] = useState<Category>("Otros");
  const create = () => { if (!term.trim()) return; const rule = { id: crypto.randomUUID(), term: term.trim(), category, custom: true }; setRules([...rules, rule]); setMovements(applyRule(movements, rule)); setTerm(""); notify("Regla creada y aplicada a movimientos anteriores"); };
  const startEdit = (rule: Rule) => { setEditing(rule.id); setDraftTerm(rule.term); setDraftCategory(rule.category); };
  const saveEdit = (rule: Rule) => { if (!draftTerm.trim()) return; const updated = { ...rule, term: draftTerm.trim(), category: draftCategory, custom: true }; const nextRules = rules.map((item) => item.id === rule.id ? updated : item); setRules(nextRules); setMovements(recategorizeUnreviewed(movements, nextRules)); setEditing(null); notify("Regla actualizada y reaplicada"); };
  const remove = (id: string) => { const nextRules = rules.filter((rule) => rule.id !== id); setRules(nextRules); setMovements(recategorizeUnreviewed(movements, nextRules)); notify("Regla eliminada"); };
  return <section className="page"><div className="page-title"><div><h1>Categorías y reglas</h1><p>Edita las reglas y reaplícalas sin perder tus correcciones manuales.</p></div></div><div className="rules-grid"><article className="card"><h2>Nueva regla</h2><p>Si concepto o descripción contiene…</p><input value={term} onChange={(e) => setTerm(e.target.value)} placeholder="Ej. Panadería Sol" /><p>Clasificar como…</p><select value={category} onChange={(e) => setCategory(e.target.value as Category)}>{CATEGORIES.map((c) => <option key={c}>{c}</option>)}</select><button className="primary full" onClick={create}>Crear y aplicar regla</button><small>Se aplicará también a los movimientos ya importados.</small><button className="secondary full" onClick={() => { setRules(DEFAULT_RULES); setMovements(recategorizeUnreviewed(movements, DEFAULT_RULES)); notify("Reglas recomendadas restauradas"); }}>Restaurar reglas recomendadas</button></article><article className="card rule-list"><div className="card-head"><div><h2>Reglas activas</h2><p>{rules.length} reglas · se evalúan en este orden</p></div></div>{rules.map((rule) => editing === rule.id ? <div className="rule-edit" key={rule.id}><input value={draftTerm} onChange={(e) => setDraftTerm(e.target.value)} aria-label="Palabras clave" /><select value={draftCategory} onChange={(e) => setDraftCategory(e.target.value as Category)}>{CATEGORIES.map((c) => <option key={c}>{c}</option>)}</select><button className="save-rule" onClick={() => saveEdit(rule)}>Guardar</button><button onClick={() => setEditing(null)}>Cancelar</button></div> : <div key={rule.id}><span>Si contiene <b>«{rule.term}»</b></span><strong>{rule.category}</strong><button aria-label={`Editar regla ${rule.term}`} onClick={() => startEdit(rule)}>Editar</button><button aria-label={`Eliminar regla ${rule.term}`} onClick={() => remove(rule.id)}>Eliminar</button></div>)}</article></div></section>;
}

function Privacy({ store, setMovements, notify }: { store: LocalDataStore; setMovements: (v: Movement[]) => void; notify: (s: string) => void }) { return <section className="page"><div className="page-title"><div><h1>Configuración y privacidad</h1></div></div><div className="privacy-grid"><article className="card setting danger"><div><h3>Eliminar todos los datos</h3><p>Borra movimientos importados y reglas personales de este dispositivo.</p></div><button onClick={() => { if (window.confirm("¿Eliminar definitivamente todos los datos guardados en este navegador? Esta acción no se puede deshacer.")) { store.clear(); setMovements([]); notify("Todos los datos se han eliminado"); } }}>Eliminar datos</button></article></div></section>; }
function Empty({ title, text, action, onAction }: { title: string; text: string; action?: string; onAction?: () => void }) { return <div className="empty"><span>€</span><h2>{title}</h2><p>{text}</p>{action && <button className="primary" onClick={onAction}>{action}</button>}</div>; }
