/* eslint-disable no-useless-escape */
import { categorize } from "./rules.ts";
import type { Movement } from "./types.ts";

export const MAX_FILE_SIZE = 5 * 1024 * 1024;
export const detectSeparator = (text: string) => [";", ",", "\t"].map((sep) => [sep, (text.split("\n")[0].match(new RegExp(sep === "\t" ? "\\t" : `\\${sep}`, "g")) || []).length] as const).sort((a, b) => b[1] - a[1])[0][0];
export function parseAmount(raw: string) { const clean = raw.trim().replace(/[^\d,.-]/g, ""); const normalized = clean.includes(",") && clean.lastIndexOf(",") > clean.lastIndexOf(".") ? clean.replaceAll(".", "").replace(",", ".") : clean.replaceAll(",", ""); const value = Number(normalized); if (!Number.isFinite(value)) throw new Error("Importe no válido"); return value; }
export function parseDate(raw: string, format = "DD/MM/YYYY") { const bits = raw.trim().split(/[\/-]/).map(Number); let d: Date; if (format === "YYYY-MM-DD") d = new Date(bits[0], bits[1] - 1, bits[2]); else if (format === "MM/DD/YYYY") d = new Date(bits[2], bits[0] - 1, bits[1]); else d = new Date(bits[2], bits[1] - 1, bits[0]); if (Number.isNaN(d.getTime()) || d.getDate() !== (format === "YYYY-MM-DD" ? bits[2] : format === "MM/DD/YYYY" ? bits[1] : bits[0])) throw new Error("Fecha no válida"); return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")}`; }
export function parseCSV(text: string, dateFormat = "DD/MM/YYYY", expensePositive = false): { rows: Movement[]; errors: number; headers: string[] } {
  const safe = text.replace(/^\uFEFF/, ""); const sep = detectSeparator(safe); const lines = safe.split(/\r?\n/).filter(Boolean); if (lines.length < 2) throw new Error("El archivo no contiene movimientos");
  const split = (line: string) => line.split(sep).map((x) => x.trim().replace(/^"|"$/g, "")); const headers = split(lines[0]).map((h) => h.toLowerCase()); let errors = 0;
  const find = (...names: string[]) => headers.findIndex((h) => names.some((n) => h.includes(n)));
  const operationDateI = headers.findIndex((h) => h.includes("fecha oper")); const dateI = operationDateI >= 0 ? operationDateI : find("fecha"); const valueDateI = headers.findIndex((h) => h.includes("fecha valor")); const conceptI = headers.findIndex((h) => h.includes("concepto")); const detailedDescriptionI = headers.findIndex((h) => h.includes("descripción") || h.includes("descripcion")); const descI = detailedDescriptionI >= 0 ? detailedDescriptionI : conceptI; const referenceI = headers.findIndex((h) => h.includes("referencia")); const amountI = find("importe"); const debitI = find("cargo"); const creditI = find("abono"); const accountI = find("cuenta", "tarjeta"); const currencyI = find("moneda");
  if (dateI < 0 || descI < 0 || (amountI < 0 && debitI < 0 && creditI < 0)) throw new Error("Faltan las columnas de fecha, descripción o importe");
  const rows = lines.slice(1).flatMap((line, index) => { try { const cells = split(line); const description = cells[descI]; if (!description) throw new Error(); let amount = amountI >= 0 ? parseAmount(cells[amountI]) : (cells[creditI] ? parseAmount(cells[creditI]) : -parseAmount(cells[debitI])); if (expensePositive && amountI >= 0) amount *= -1; const match = categorize(`${conceptI >= 0 ? cells[conceptI] : ""} ${description}`); const operationDate = parseDate(cells[dateI], dateFormat); return [{ id: `csv-${Date.now()}-${index}`, date: operationDate, valueDate: valueDateI >= 0 && cells[valueDateI] ? parseDate(cells[valueDateI], dateFormat) : operationDate, concept: conceptI >= 0 ? cells[conceptI]?.replace(/^[=+@]/, "'") : undefined, reference: referenceI >= 0 ? cells[referenceI]?.replace(/^[=+@]/, "'") : undefined, description: description.replace(/^[=+@]/, "'"), merchant: description.replace(/\b(compra|pago|recibo|tarjeta)\b/gi, "").trim(), category: match.category, account: accountI >= 0 ? cells[accountI] || "Cuenta importada" : "Cuenta importada", amount, currency: (currencyI >= 0 ? cells[currencyI] : "EUR") === "EUR" ? "EUR" as const : "EUR" as const, status: "pendiente" as const, reason: match.reason, source: "csv" as const }]; } catch { errors++; return []; } });
  return { rows, errors, headers };
}
